site_name: Cloud4RPi Documentation

pages:
- Home: index.md
- HTTP API: http_api.md
- MQTT API: mqtt_api.md
- How To: howto.md
- FAQ: faq.md

markdown_extensions:
    - admonition:

extra_css: [extra.css]
theme: mkdocs
