site_name: Cloud4Rpi Documentation

pages:
- Home: index.md
- Typical Scenarios: typical-scenarios.md
- FAQ: faq.md
- HTTP API: http_api.md

markdown_extensions:
    - admonition:

extra_css: [extra.css]
theme: mkdocs